In [1]:
# Python

In [10]:
a = 2

In [11]:
print(a)

2


In [12]:
b = 86869896896986968966866676757547467

In [13]:
print(b)

86869896896986968966866676757547467


In [14]:
c = 3.123345

In [15]:
c

3.123345

In [16]:
d = 'artificial intell'

In [17]:
d

'artificial intell'

In [18]:
e = True

In [19]:
e

True

In [20]:
f = None

In [21]:
print(f)

None


In [22]:
AI__a_101_course = 120

In [ ]:
import keyword

In [ ]:
print(keyword.kwlist)

In [ ]:
x = 90
y = x*10 + x**x

In [ ]:
print(y)

In [ ]:
# data types:

# integer
# string
# float

# arrays (scalar, vector, matrix, array, multidimensional array)

# list
# set
# dict
# tuple
# boolean
# null


In [ ]:
# multiple values, multiple variables

In [ ]:
t, d, f, h = 1,2,34,5

In [ ]:
print(t, d, f, h)

In [ ]:
t, d, f, _ = 1,2,34,5 # splitting train test data, retirving model parameters

In [ ]:
print(t, d, f)

In [ ]:
t, d, f, h = 1,2,34, None # feature engineering, feature selection

In [ ]:
print(t, d, f, h)

In [ ]:
d = [1,2,34,5]

In [ ]:
d

In [ ]:
# cascading assignment

In [ ]:
a = b = c = d = 1001

In [ ]:
a

In [ ]:
b

In [ ]:
c

In [ ]:
d

In [ ]:
b = 2001

In [ ]:
print(a,b,c,d)

In [ ]:
# this is possible if we are using a mutable data type

In [ ]:
x = y = [90,80,70]

In [ ]:
x

In [ ]:
y

In [ ]:
x = [1,2,3,4,5]

In [ ]:
y

In [ ]:
x

In [ ]:
# changing x as a list did not impact the y value

In [ ]:
x = y = [90,80,70]

In [ ]:
x

In [ ]:
y

In [ ]:
x[0] = 9000

In [ ]:
print(y)

In [ ]:
# list 
d = [['1','2'],[34.],[5]]

In [ ]:
d

In [ ]:
d[0][0]

In [24]:
d = ['1','2',34,5]

In [25]:
d

['1', '2', 34, 5]

In [26]:
d = [1.,2.0,34.8,5]

In [27]:
d

[1.0, 2.0, 34.8, 5]

In [1]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [29]:
import numpy as np

In [30]:
d1 = np.array(d)

In [31]:
type(d1)

numpy.ndarray

In [32]:
d1

array([ 1. ,  2. , 34.8,  5. ])

In [33]:
d1.reshape(2,2).flatten()

array([ 1. ,  2. , 34.8,  5. ])

In [34]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [35]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [36]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [37]:
# 

In [38]:
d = (5.11,78) # tuple

In [39]:
d

(5.11, 78)

In [40]:
{"name": ['pm','sm'],
"age": [12,23]}

{'name': ['pm', 'sm'], 'age': [12, 23]}

In [41]:
d1 = tuple(d1)

In [42]:
d1

(1.0, 2.0, 34.8, 5.0)

In [43]:
d = [True, False, True]

In [44]:
d

[True, False, True]

In [45]:
d = [0,1,0,1]

In [46]:
d

[0, 1, 0, 1]

In [47]:
t = ('we','are','going','to','learn','data')

In [48]:
t

('we', 'are', 'going', 'to', 'learn', 'data')

In [49]:
t[5]

'data'

In [50]:
text = '''I am going to learn data science in Reva Univ'''

In [51]:
text

'I am going to learn data science in Reva Univ'

In [52]:
t = text.split()

In [53]:
t

['I', 'am', 'going', 'to', 'learn', 'data', 'science', 'in', 'Reva', 'Univ']

In [54]:
t[-7:-6]

['to']

In [55]:
len(t)

10

In [56]:
len(t)

10

In [57]:
t[:8]

['I', 'am', 'going', 'to', 'learn', 'data', 'science', 'in']

In [58]:
t[:-2]

['I', 'am', 'going', 'to', 'learn', 'data', 'science', 'in']

In [59]:
# set = {12,23,(34,45,56)} # this line basically modifies the built-in function 'set' 

In [60]:
# set

In [61]:
c = 8.767868678578578576746533577467458

In [62]:
np.round(np.pi,8)

3.14159265

In [63]:
# Problem:

# N-element tuple or sequence that need unpacking into a collection of variables
# how you are going to do ?


In [64]:
# Answer:

In [65]:
p = (78, 25)

In [66]:
p

(78, 25)

In [67]:
# assignment operator
x, y = p

In [68]:
print(x)

78


In [69]:
print(y)

25


In [70]:
data = ['APPLE',120,12.4,(2020,9,5),('morning','day', 'evening')]

In [71]:
data

['APPLE', 120, 12.4, (2020, 9, 5), ('morning', 'day', 'evening')]

In [72]:
type(data)

list

In [73]:
org_name, share_price, delta_change, date, timing = data

In [74]:
date

(2020, 9, 5)

In [75]:
org_name

'APPLE'

In [76]:
timing

('morning', 'day', 'evening')

In [77]:
org_name, share_price, delta_change, date,_ = data

In [78]:
print(_)

('morning', 'day', 'evening')


In [79]:
# Variables

In [80]:
data = 'i am learning data science'

In [81]:
data

'i am learning data science'

In [82]:
data = 'i am learning data science, also AI'

In [83]:
data

'i am learning data science, also AI'

In [84]:
data = 'i am learning data science'
print(data)
data = 'i am learning data science, also AI'
print(data)

i am learning data science
i am learning data science, also AI


In [85]:
# letters
# numbers
# underscores

In [86]:
# variables names cannot start with a number
# avoid spaces, replace them with underscore
# cannot use Keywords as variable names
# 

In [87]:
help()


Welcome to Python 3.8's help utility!

If this is your first time using Python, you should definitely check out
the tutorial on the Internet at https://docs.python.org/3.8/tutorial/.

Enter the name of any module, keyword, or topic to get help on writing
Python programs and using Python modules.  To quit this help utility and
return to the interpreter, just type "quit".

To get a list of available modules, keywords, symbols, or topics, type
"modules", "keywords", "symbols", or "topics".  Each module also comes
with a one-line summary of what it does; to list the modules whose name
or summary contain a given string such as "spam", type "modules spam".

help> quit

You are now leaving help and returning to the Python interpreter.
If you want to ask for help on a particular object directly from the
interpreter, you can type "help(object)".  Executing "help('string')"
has the same effect as typing a particular string at the help> prompt.


In [88]:
keywords = ['False asSignment','Nan',' def','elif','return']

In [89]:
keywords

['False asSignment', 'Nan', ' def', 'elif', 'return']

In [90]:
for word in keywords:
    print(word.title())

False Assignment
Nan
 Def
Elif
Return


In [91]:
word.title()

'Return'

In [92]:
keywords[0]

'False asSignment'

In [93]:
keywords[4]

'return'

In [96]:
list1 = [12,23,34,45]
list2 = [0.2,5,'Python','#','!','@','None',None, False]

In [97]:
list2

[0.2, 5, 'Python', '#', '!', '@', 'None', None, False]

In [98]:
list2[5] = 'Twitter_Handle'

In [99]:
list2

[0.2, 5, 'Python', '#', '!', 'Twitter_Handle', 'None', None, False]

In [100]:
del list2[4]

In [101]:
list2

[0.2, 5, 'Python', '#', 'Twitter_Handle', 'None', None, False]

In [102]:
if 'python' in list2:
    print('Yes')
else:
    print('No')

No


In [103]:
# functions
# built-in, custom

In [104]:
a = [12,23,34,45,56,67,78,89,90]
a

[12, 23, 34, 45, 56, 67, 78, 89, 90]

In [105]:
np.mean(a)

54.888888888888886

In [106]:
def average(x):
    return np.sum(x)/len(x)

In [107]:
average(a)

54.888888888888886

In [108]:
# Mutability of list

In [109]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [110]:
list2

[0.2, 5, 'Python', '#', 'Twitter_Handle', 'None', None, False]

In [111]:
list2[3] = 99

In [112]:
list2

[0.2, 5, 'Python', 99, 'Twitter_Handle', 'None', None, False]

In [113]:
list2.append('data analysis')

In [114]:
list2

[0.2, 5, 'Python', 99, 'Twitter_Handle', 'None', None, False, 'data analysis']

In [115]:
list2.remove('None')

In [116]:
list2

[0.2, 5, 'Python', 99, 'Twitter_Handle', None, False, 'data analysis']

In [118]:
list21 = ['at', 'python','pat','abcd','e','c', 'data analysis']

In [119]:
list21

['at', 'python', 'pat', 'abcd', 'e', 'c', 'data analysis']

In [120]:
list21.sort(reverse=True)

In [121]:
#help(list21.sort)

In [122]:
list21

['python', 'pat', 'e', 'data analysis', 'c', 'at', 'abcd']

In [123]:
list21.sort(key=len)

In [124]:
list21

['e', 'c', 'at', 'pat', 'abcd', 'python', 'data analysis']

In [125]:
sorted(list21,key=len)

['e', 'c', 'at', 'pat', 'abcd', 'python', 'data analysis']

In [126]:
list21

['e', 'c', 'at', 'pat', 'abcd', 'python', 'data analysis']

In [127]:
list21.sort(reverse=False)

In [128]:
list21

['abcd', 'at', 'c', 'data analysis', 'e', 'pat', 'python']

In [129]:
list22 = [0.2,5,6,12,3,45,5]

In [130]:
list22.sort()

In [131]:
list22

[0.2, 3, 5, 5, 6, 12, 45]

In [132]:
sorted(list22)

[0.2, 3, 5, 5, 6, 12, 45]

In [134]:
numbers = (2,4,1,2,5,6)

In [135]:
numbers

(2, 4, 1, 2, 5, 6)

In [136]:
sorted(numbers)

[1, 2, 2, 4, 5, 6]

In [137]:
numbers = {2,4,1,2,5,6}

In [138]:
numbers

{1, 2, 4, 5, 6}

In [139]:
sorted(numbers,reverse=True)

[6, 5, 4, 2, 1]

In [140]:
dt = {"ram":1, "alpha": 2, "beta":4, "data": 5, "gama": 6}

In [141]:
dt

{'ram': 1, 'alpha': 2, 'beta': 4, 'data': 5, 'gama': 6}

In [142]:
sorted(dt.values(),reverse=True)

[6, 5, 4, 2, 1]

In [143]:
sorted(dt.keys(),reverse=True)

['ram', 'gama', 'data', 'beta', 'alpha']

In [144]:
sorted(dt.items(),reverse=True)

[('ram', 1), ('gama', 6), ('data', 5), ('beta', 4), ('alpha', 2)]

In [145]:
sorted(dt.items(),reverse=False)

[('alpha', 2), ('beta', 4), ('data', 5), ('gama', 6), ('ram', 1)]

In [146]:
import os

In [147]:
import pandas as pd

In [148]:
df = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/bag-of-words/vocab.nips.txt',sep='\s+')

In [149]:
'access' in list(df.a2i)

True

In [150]:
df.head()

a2i
0      aaa
1     aaai
2     aapo
3      aat
4  aazhang

In [151]:
df = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/00591/name_gender_dataset.csv')

In [152]:
df.head()

Name Gender    Count  Probability
0    James      M  5304407     0.014517
1     John      M  5260831     0.014398
2   Robert      M  4970386     0.013603
3  Michael      M  4579950     0.012534
4  William      M  4226608     0.011567

In [153]:
df[df.Name == 'James']

Name Gender    Count  Probability
0     James      M  5304407     0.014517
1615  James      F    23963     0.000066

In [154]:
# Problem statement:

In [155]:
# Two columns 
ProbA = [0.01,0.20,0.21,0.2,0.3,0.5,0.49,0.51]
ProbB = [0.99,0.80,0.79,0.8,0.7,0.5,0.51,0.49]

In [156]:
ProbA

[0.01, 0.2, 0.21, 0.2, 0.3, 0.5, 0.49, 0.51]

In [157]:
ProbB

[0.99, 0.8, 0.79, 0.8, 0.7, 0.5, 0.51, 0.49]

In [158]:
# ProbA= Approved
# ProbB= Canceled

In [159]:
# if any two sum of probabilities are equal to 0.7 or 0.8 (threshold), then return True else False

In [160]:
#example
list123 = [0.10,0.15,0.30,0.7]

In [161]:
threshold = 0.80
# (0.10,0.7) = 0.8, return True or False

In [162]:
# write a custom function for the above task

In [163]:
# Close Solution, values and all combination
def get_sum(num,thres):
    for i in range(len(num)):
        for j in range(i+1,len(num)):
            if num[i]+num[j] == thres:
                return(i,j)

In [164]:
np.round((0.10+0.70),2)

0.8

In [165]:
get_sum(list123,0.8)

In [166]:
get_sum(ProbA,0.8)

(4, 5)

In [167]:
ProbA[4] + ProbA[5]

0.8

In [168]:
0.3 + 0.5

0.8

In [169]:
0.1 + 0.7

0.7999999999999999

In [170]:
# Think about the issues

In [171]:
# Near Perfect Solution- need to print all such instances
def findAmb(threshold, probList) :
    list2 = [];
    for num in probList:
        #print(num)
        dif = threshold - num
        #print(dif)
        if( round(dif, 2) in probList):
            list2.append(num)
    return list2

In [172]:
findAmb(0.8,ProbA)

[0.3, 0.5]

In [173]:
# Best Solution
#helper func for probablity
def func_prob_check(class_arr,thres):
    count=0
    for i in class_arr:
        #print(i)
        count= count +1
        #print(count,len(class_arr)-count)
        child_arr =class_arr[count:]
        #print(child_arr)
        for j in child_arr:
        #print (j)
            if i!=j:
                if (i+j) >= thres:
                    print ("Prob Threshold values : (" , i ,",",j ,") =" , i+j)

In [174]:
func_prob_check(ProbA,0.8)

Prob Threshold values : ( 0.3 , 0.5 ) = 0.8
Prob Threshold values : ( 0.3 , 0.51 ) = 0.81
Prob Threshold values : ( 0.5 , 0.49 ) = 0.99
Prob Threshold values : ( 0.5 , 0.51 ) = 1.01
Prob Threshold values : ( 0.49 , 0.51 ) = 1.0


In [175]:
def my_calc():
    bmi = 25
    return bmi
print(my_calc())

25


In [176]:
bmi = 26
if bmi > 25: print('over-weight'),print('obese')
else:print('normal')

over-weight
obese


In [177]:
bmi = 25
if bmi > 25: print('over-weight'),print('obese')
else:print('normal')

normal


In [178]:
# data type conversion

In [179]:
a = '123'

In [180]:
type(a)

str

In [181]:
num = int(a)

In [182]:
type(num)

int

In [183]:
b = float(a)
type(b)

float

In [184]:
# mutable object and immutable object

In [185]:
ProbA

[0.01, 0.2, 0.21, 0.2, 0.3, 0.5, 0.49, 0.51]

In [186]:
type(ProbA)

list

In [187]:
def average(x):
    return np.mean(x)

In [188]:
average(ProbA)

0.3025

In [189]:
def somef():
    x = (10,11)
    g(x)
    x == (10,11)

In [190]:
a = 10
a = a + 12

In [191]:
a

22

In [192]:
# Immutable data types
# int, long, float, complex
# str, bytes, tuple

In [193]:
# mutable data types
# list
# set
# dict
# bytearray

In [194]:
def f(m):
    m.append(3)
    
x = [1,2]
f(x)
x == [1,2]

False

In [195]:
x

[1, 2, 3]

In [197]:
names = list(df.Name)
names

['James',
 'John',
 'Robert',
 'Michael',
 'William',
 'Mary',
 'David',
 'Joseph',
 'Richard',
 'Charles',
 'Thomas',
 'Christopher',
 'Daniel',
 'Matthew',
 'Elizabeth',
 'Patricia',
 'Jennifer',
 'Anthony',
 'George',
 'Linda',
 'Barbara',
 'Donald',
 'Paul',
 'Mark',
 'Andrew',
 'Steven',
 'Kenneth',
 'Edward',
 'Joshua',
 'Margaret',
 'Brian',
 'Kevin',
 'Jessica',
 'Sarah',
 'Susan',
 'Timothy',
 'Dorothy',
 'Jason',
 'Ronald',
 'Helen',
 'Ryan',
 'Jeffrey',
 'Karen',
 'Nancy',
 'Betty',
 'Lisa',
 'Jacob',
 'Nicholas',
 'Ashley',
 'Eric',
 'Frank',
 'Gary',
 'Anna',
 'Stephen',
 'Jonathan',
 'Sandra',
 'Emily',
 'Amanda',
 'Kimberly',
 'Michelle',
 'Donna',
 'Justin',
 'Laura',
 'Ruth',
 'Carol',
 'Brandon',
 'Larry',
 'Scott',
 'Melissa',
 'Stephanie',
 'Benjamin',
 'Raymond',
 'Samuel',
 'Rebecca',
 'Deborah',
 'Gregory',
 'Sharon',
 'Kathleen',
 'Amy',
 'Cynthia',
 'Alexander',
 'Patrick',
 'Jack',
 'Henry',
 'Angela',
 'Shirley',
 'Emma',
 'Catherine',
 'Katherine',
 'Virgini

In [198]:
'Charles' in names

True

In [199]:
names.index('Charles')

9

In [200]:
names[9]

'Charles'

In [201]:
names.append('Ann')

In [202]:
names.index('Ann')

134

In [203]:
names.insert(0,'Bob')

In [204]:
names

['Bob',
 'James',
 'John',
 'Robert',
 'Michael',
 'William',
 'Mary',
 'David',
 'Joseph',
 'Richard',
 'Charles',
 'Thomas',
 'Christopher',
 'Daniel',
 'Matthew',
 'Elizabeth',
 'Patricia',
 'Jennifer',
 'Anthony',
 'George',
 'Linda',
 'Barbara',
 'Donald',
 'Paul',
 'Mark',
 'Andrew',
 'Steven',
 'Kenneth',
 'Edward',
 'Joshua',
 'Margaret',
 'Brian',
 'Kevin',
 'Jessica',
 'Sarah',
 'Susan',
 'Timothy',
 'Dorothy',
 'Jason',
 'Ronald',
 'Helen',
 'Ryan',
 'Jeffrey',
 'Karen',
 'Nancy',
 'Betty',
 'Lisa',
 'Jacob',
 'Nicholas',
 'Ashley',
 'Eric',
 'Frank',
 'Gary',
 'Anna',
 'Stephen',
 'Jonathan',
 'Sandra',
 'Emily',
 'Amanda',
 'Kimberly',
 'Michelle',
 'Donna',
 'Justin',
 'Laura',
 'Ruth',
 'Carol',
 'Brandon',
 'Larry',
 'Scott',
 'Melissa',
 'Stephanie',
 'Benjamin',
 'Raymond',
 'Samuel',
 'Rebecca',
 'Deborah',
 'Gregory',
 'Sharon',
 'Kathleen',
 'Amy',
 'Cynthia',
 'Alexander',
 'Patrick',
 'Jack',
 'Henry',
 'Angela',
 'Shirley',
 'Emma',
 'Catherine',
 'Katherine',
 

In [205]:
names.remove('Ann')

In [206]:
names.index('Ann')

9378

In [207]:
names

['Bob',
 'James',
 'John',
 'Robert',
 'Michael',
 'William',
 'Mary',
 'David',
 'Joseph',
 'Richard',
 'Charles',
 'Thomas',
 'Christopher',
 'Daniel',
 'Matthew',
 'Elizabeth',
 'Patricia',
 'Jennifer',
 'Anthony',
 'George',
 'Linda',
 'Barbara',
 'Donald',
 'Paul',
 'Mark',
 'Andrew',
 'Steven',
 'Kenneth',
 'Edward',
 'Joshua',
 'Margaret',
 'Brian',
 'Kevin',
 'Jessica',
 'Sarah',
 'Susan',
 'Timothy',
 'Dorothy',
 'Jason',
 'Ronald',
 'Helen',
 'Ryan',
 'Jeffrey',
 'Karen',
 'Nancy',
 'Betty',
 'Lisa',
 'Jacob',
 'Nicholas',
 'Ashley',
 'Eric',
 'Frank',
 'Gary',
 'Anna',
 'Stephen',
 'Jonathan',
 'Sandra',
 'Emily',
 'Amanda',
 'Kimberly',
 'Michelle',
 'Donna',
 'Justin',
 'Laura',
 'Ruth',
 'Carol',
 'Brandon',
 'Larry',
 'Scott',
 'Melissa',
 'Stephanie',
 'Benjamin',
 'Raymond',
 'Samuel',
 'Rebecca',
 'Deborah',
 'Gregory',
 'Sharon',
 'Kathleen',
 'Amy',
 'Cynthia',
 'Alexander',
 'Patrick',
 'Jack',
 'Henry',
 'Angela',
 'Shirley',
 'Emma',
 'Catherine',
 'Katherine',
 

In [208]:
df.Name.value_counts()

Nia          2
Jarden       2
Steve        2
Brodee       2
Marciel      2
            ..
Mouad        1
Che'         1
Kynslei      1
Lillienne    1
Triestina    1
Name: Name, Length: 133910, dtype: int64

In [209]:
names = list(df.Name.unique())

In [210]:
len(names)

133910

In [211]:
df.shape

(147269, 4)

In [212]:
names1 = list(df.Name)

In [213]:
names.count('Bob')

1

In [214]:
names1.count('Bob')

2

In [215]:
names.pop(names.index('Bob'))

'Bob'

In [217]:
names.index('Ann')

134

In [218]:
names1.pop(names1.index('Bob'))

'Bob'

In [219]:
names1.index('Bob')

23497

In [220]:
names1.remove('Indu')

In [221]:
names1.index('Indu')

138684

In [222]:
names2 = list(df[df.Name != 'Jemmie'].Name)

In [224]:
# Tuple
ip_add = ('10.20.30.400', 8080)

In [225]:
# Dictionaries

In [226]:
this_dict = {}

In [227]:
this_dict = {'Age': 25, "Gender": 'male' , 'Exxp': 12}

In [228]:
this_dict

{'Age': 25, 'Gender': 'male', 'Exxp': 12}

In [229]:
this_dict.keys()

dict_keys(['Age', 'Gender', 'Exxp'])

In [230]:
this_dict.values()

dict_values([25, 'male', 12])

In [231]:
this_dict.items()

dict_items([('Age', 25), ('Gender', 'male'), ('Exxp', 12)])

In [232]:
this_dict2 = dict(Age= [25,26], Gender= 'male' , Exxp = 12)

In [233]:
this_dict2

{'Age': [25, 26], 'Gender': 'male', 'Exxp': 12}

In [234]:
this_dict == this_dict2

False

In [235]:
this_dict2['Exxp'] = 21

In [236]:
this_dict2

{'Age': [25, 26], 'Gender': 'male', 'Exxp': 21}

In [237]:
del this_dict2['Exxp']

In [238]:
this_dict2

{'Age': [25, 26], 'Gender': 'male'}

In [239]:
this_dict2['Age'][0] = 27

In [240]:
this_dict2

{'Age': [27, 26], 'Gender': 'male'}

In [241]:
this_dict

{'Age': 25, 'Gender': 'male', 'Exxp': 12}

In [242]:
this_dict2

{'Age': [27, 26], 'Gender': 'male'}

In [243]:
this_dict.update(this_dict2)

In [244]:
this_dict

{'Age': [27, 26], 'Gender': 'male', 'Exxp': 12}

In [245]:
# Problem Statement
# Moving averages - arithmatic mean

In [246]:
d = np.array([120,23,34,45,56,67,78,89])

In [247]:
d.mean()

64.0

In [248]:
# running median leaving one record out

In [249]:
# missing value imputation
# column mean as replacement for missing values

In [250]:
# running median - more closer to the missing data

In [251]:
d

array([120,  23,  34,  45,  56,  67,  78,  89])

In [252]:
# can you create a custom function to populate running median of the above series.

In [253]:
d.sort()

In [254]:
d

array([ 23,  34,  45,  56,  67,  78,  89, 120])

In [255]:
(len(d)+1)/2

4.5

In [256]:
(56+67)/2

61.5

In [257]:
np.median(d)

61.5

In [258]:
d

array([ 23,  34,  45,  56,  67,  78,  89, 120])

In [259]:
window_size = 2

series = pd.Series(d)
blocks = series.rolling(window_size)
rolling_mean = blocks.mean()
print(rolling_mean)

0      NaN
1     28.5
2     39.5
3     50.5
4     61.5
5     72.5
6     83.5
7    104.5
dtype: float64


In [260]:
d = np.array([120,23,34,45,56,67,78,89])
window_size = 3
print(d)
series = pd.Series(d)
blocks = series.rolling(window_size)
rolling_mean = blocks.mean()
print(rolling_mean)

[120  23  34  45  56  67  78  89]
0     NaN
1     NaN
2    59.0
3    34.0
4    45.0
5    56.0
6    67.0
7    78.0
dtype: float64


def get_med(arr):
    arr.sort()
    print(arr)
    x = int(round(len(arr)/2,0))
    print(x)
    med = (arr[x]+arr[x-1])/2
    return med

get_med(d)

In [261]:
df

Name Gender    Count   Probability
0         James      M  5304407  1.451679e-02
1          John      M  5260831  1.439753e-02
2        Robert      M  4970386  1.360266e-02
3       Michael      M  4579950  1.253414e-02
4       William      M  4226608  1.156713e-02
...         ...    ...      ...           ...
147264   Zylenn      M        1  2.736740e-09
147265   Zymeon      M        1  2.736740e-09
147266   Zyndel      M        1  2.736740e-09
147267   Zyshan      M        1  2.736740e-09
147268    Zyton      M        1  2.736740e-09

[147269 rows x 4 columns]

In [271]:
set(df.Name)

{'Walt',
 'Fintan',
 'Wyatte',
 'Tatianya',
 'Kavion',
 'Patyn',
 'Huk',
 'Kayanda',
 'Yendriel',
 'Shinobi',
 'Tikeria',
 'Adayah',
 'Akeil',
 'Leward',
 'Nikoll',
 'Rychard',
 'Alliera',
 'Yeoryi',
 'Aalla',
 'Deshaun',
 'Amenda',
 'Trania',
 'Rikki',
 'Jemille',
 'Willim',
 'Treacy',
 'Advaita',
 'Yameka',
 'Shaunece',
 'Serguio',
 'Xhaiden',
 'Tyjohn',
 'Talisia',
 'Tasheen',
 'Yasmene',
 'Julliet',
 'Isiash',
 'Monissa',
 'Vageli',
 'Tarrant',
 'Treyah',
 'Sharalee',
 'Avraham',
 'Caeghan',
 'Yuisa',
 'Kalika',
 'Aerianna',
 'Robyne',
 'Caisen',
 'Jobyna',
 'Yovela',
 'Yuriy',
 'Kennedi',
 'Daneil',
 'Benjen',
 'Aurelius',
 'Turk',
 'Skyee',
 'Haofeng',
 'Gracelyn',
 'Caliese',
 'Kalob',
 'Cirrus',
 'Felicitas',
 'Kaylanna',
 'Jenssen',
 'Ralphine',
 'Valdon',
 'Iyanu',
 'Dremond',
 'Kyshia',
 'Avetis',
 'Brayli',
 'Titu@Devender',
 'Kimon',
 'Audryana',
 'Nail',
 'Tyzana',
 'Rutvij',
 'Mazni',
 'Merici',
 'Traelyn',
 'Columbus',
 'Amoha',
 'Kalliope',
 'Nashelle',
 'Gwilym',
 'Ir

In [263]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 147269 entries, 0 to 147268
Data columns (total 4 columns):
 #   Column       Non-Null Count   Dtype  
---  ------       --------------   -----  
 0   Name         147269 non-null  object 
 1   Gender       147269 non-null  object 
 2   Count        147269 non-null  int64  
 3   Probability  147269 non-null  float64
dtypes: float64(1), int64(1), object(2)
memory usage: 4.5+ MB


In [264]:
import pandas as pd

In [265]:
pd.__version__

'1.2.2'

In [266]:
df_new = pd.read_csv('https://gist.githubusercontent.com/seankross/a412dfbd88b3db70b74b/raw/5f23f993cd87c283ce766e7ac6b329ee7cc2e1d1/mtcars.csv')

In [267]:
list(df_new.model)

['Mazda RX4',
 'Mazda RX4 Wag',
 'Datsun 710',
 'Hornet 4 Drive',
 'Hornet Sportabout',
 'Valiant',
 'Duster 360',
 'Merc 240D',
 'Merc 230',
 'Merc 280',
 'Merc 280C',
 'Merc 450SE',
 'Merc 450SL',
 'Merc 450SLC',
 'Cadillac Fleetwood',
 'Lincoln Continental',
 'Chrysler Imperial',
 'Fiat 128',
 'Honda Civic',
 'Toyota Corolla',
 'Toyota Corona',
 'Dodge Challenger',
 'AMC Javelin',
 'Camaro Z28',
 'Pontiac Firebird',
 'Fiat X1-9',
 'Porsche 914-2',
 'Lotus Europa',
 'Ford Pantera L',
 'Ferrari Dino',
 'Maserati Bora',
 'Volvo 142E']

In [272]:
# set issue in this notebook

# make sure you are not overwriting the built in functions of python 

In [273]:
set(df_new.cyl)

{4, 6, 8}

In [274]:
# Modules and Function

In [275]:
pow(3,4)

81

In [277]:
dir(__builtins__)

['ArithmeticError',
 'AssertionError',
 'AttributeError',
 'BaseException',
 'BlockingIOError',
 'BrokenPipeError',
 'BufferError',
 'BytesWarning',
 'ChildProcessError',
 'ConnectionAbortedError',
 'ConnectionError',
 'ConnectionRefusedError',
 'ConnectionResetError',
 'DeprecationWarning',
 'EOFError',
 'Ellipsis',
 'EnvironmentError',
 'Exception',
 'False',
 'FileExistsError',
 'FileNotFoundError',
 'FloatingPointError',
 'FutureWarning',
 'GeneratorExit',
 'IOError',
 'ImportError',
 'ImportWarning',
 'IndentationError',
 'IndexError',
 'InterruptedError',
 'IsADirectoryError',
 'KeyError',
 'KeyboardInterrupt',
 'LookupError',
 'MemoryError',
 'ModuleNotFoundError',
 'NameError',
 'None',
 'NotADirectoryError',
 'NotImplemented',
 'NotImplementedError',
 'OSError',
 'OverflowError',
 'PendingDeprecationWarning',
 'PermissionError',
 'ProcessLookupError',
 'RecursionError',
 'ReferenceError',
 'ResourceWarning',
 'RuntimeError',
 'RuntimeWarning',
 'StopAsyncIteration',
 'StopIter

In [278]:
dir(__import__)

['__call__',
 '__class__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__name__',
 '__ne__',
 '__new__',
 '__qualname__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__self__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__text_signature__']

In [279]:
dir(__name__)

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getnewargs__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmod__',
 '__rmul__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'capitalize',
 'casefold',
 'center',
 'count',
 'encode',
 'endswith',
 'expandtabs',
 'find',
 'format',
 'format_map',
 'index',
 'isalnum',
 'isalpha',
 'isascii',
 'isdecimal',
 'isdigit',
 'isidentifier',
 'islower',
 'isnumeric',
 'isprintable',
 'isspace',
 'istitle',
 'isupper',
 'join',
 'ljust',
 'lower',
 'lstrip',
 'maketrans',
 'partition',
 'replace',
 'rfind',
 'rindex',
 'rjust',
 'rpartition',
 'rsplit',
 'rstrip',
 'split',
 'splitlines',
 'startswith',
 'strip',
 'swapcase',
 'title',
 'translate',
 'upper',


In [280]:
dir(__package__)

['__bool__',
 '__class__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__']

In [281]:
help(max)

Help on built-in function max in module builtins:

max(...)
    max(iterable, *[, default=obj, key=func]) -> value
    max(arg1, arg2, *args, *[, key=func]) -> value
    
    With a single iterable argument, return its biggest item. The
    default keyword-only argument specifies an object to return if
    the provided iterable is empty.
    With two or more arguments, return the largest argument.



In [282]:
import math

In [283]:
math.sqrt(89)

9.433981132056603

In [286]:
print(dir(math))

['__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', 'acos', 'acosh', 'asin', 'asinh', 'atan', 'atan2', 'atanh', 'ceil', 'comb', 'copysign', 'cos', 'cosh', 'degrees', 'dist', 'e', 'erf', 'erfc', 'exp', 'expm1', 'fabs', 'factorial', 'floor', 'fmod', 'frexp', 'fsum', 'gamma', 'gcd', 'hypot', 'inf', 'isclose', 'isfinite', 'isinf', 'isnan', 'isqrt', 'ldexp', 'lgamma', 'log', 'log10', 'log1p', 'log2', 'modf', 'nan', 'perm', 'pi', 'pow', 'prod', 'radians', 'remainder', 'sin', 'sinh', 'sqrt', 'tan', 'tanh', 'tau', 'trunc']


In [287]:
math.__doc__

'This module provides access to the mathematical functions\ndefined by the C standard.'

In [289]:
import datetime

In [290]:
datetime.datetime.now()

datetime.datetime(2021, 4, 10, 16, 8, 57, 489478)

In [ ]:
# if statememnts

In [291]:
fruits = ['apple','orange','banana','cookies']

In [292]:
fav_fruit = 'apple'

In [293]:
for fruit in fruits:
    if fruit == fav_fruit:
        print(fruit)
    else:
        print('none')

apple
none
none
none


==
!=
>=
<=
<
>

In [ ]:
# list comprehension

In [294]:
d

array([120,  23,  34,  45,  56,  67,  78,  89])

In [295]:
d = list(d)

In [296]:
d

[120, 23, 34, 45, 56, 67, 78, 89]

In [297]:
[a**2 for a in d]

[14400, 529, 1156, 2025, 3136, 4489, 6084, 7921]

In [ ]:
# string operations

In [298]:
sent1 = '''With the growing adoption of "machine learning" techniques, there is an increasing demand for research towards making machine learning models transparent and interpretable'''

In [299]:
sent1

'With the growing adoption of "machine learning" techniques, there is an increasing demand for research towards making machine learning models transparent and interpretable'

In [300]:
sent1.upper()

'WITH THE GROWING ADOPTION OF "MACHINE LEARNING" TECHNIQUES, THERE IS AN INCREASING DEMAND FOR RESEARCH TOWARDS MAKING MACHINE LEARNING MODELS TRANSPARENT AND INTERPRETABLE'

In [301]:
sent1.lower()

'with the growing adoption of "machine learning" techniques, there is an increasing demand for research towards making machine learning models transparent and interpretable'

In [302]:
sent1*3

'With the growing adoption of "machine learning" techniques, there is an increasing demand for research towards making machine learning models transparent and interpretableWith the growing adoption of "machine learning" techniques, there is an increasing demand for research towards making machine learning models transparent and interpretableWith the growing adoption of "machine learning" techniques, there is an increasing demand for research towards making machine learning models transparent and interpretable'

In [303]:
sent1

'With the growing adoption of "machine learning" techniques, there is an increasing demand for research towards making machine learning models transparent and interpretable'

In [306]:
sent1 = '''   With the growing adoption of "machine learning"    techniques, there is an increasing demand for  '''

In [307]:
sent1

'   With the growing adoption of "machine learning"    techniques, there is an increasing demand for  '

In [308]:
sent1.strip()

'With the growing adoption of "machine learning"    techniques, there is an increasing demand for'

In [309]:
sent1.lstrip()

'With the growing adoption of "machine learning"    techniques, there is an increasing demand for  '

In [310]:
sent1.rstrip()

'   With the growing adoption of "machine learning"    techniques, there is an increasing demand for'

In [311]:
sent2 = sent1.split()

In [312]:
for word in sent2:
     print(word.upper())

WITH
THE
GROWING
ADOPTION
OF
"MACHINE
LEARNING"
TECHNIQUES,
THERE
IS
AN
INCREASING
DEMAND
FOR


In [ ]:
# reading and getting external data for analysis

In [313]:
import pandas as pd

In [314]:
df = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/auto-mpg/auto-mpg.data',
                 header=None,
                 sep='\s+')

In [315]:
df.head()

0  1      2      3       4     5   6  7                          8
0  18.0  8  307.0  130.0  3504.0  12.0  70  1  chevrolet chevelle malibu
1  15.0  8  350.0  165.0  3693.0  11.5  70  1          buick skylark 320
2  18.0  8  318.0  150.0  3436.0  11.0  70  1         plymouth satellite
3  16.0  8  304.0  150.0  3433.0  12.0  70  1              amc rebel sst
4  17.0  8  302.0  140.0  3449.0  10.5  70  1                ford torino

In [316]:
'''1. mpg: continuous
2. cylinders: multi-valued discrete
3. displacement: continuous
4. horsepower: continuous
5. weight: continuous
6. acceleration: continuous
7. model year: multi-valued discrete
8. origin: multi-valued discrete
9. car name: string (unique for each instance)'''

'1. mpg: continuous\n2. cylinders: multi-valued discrete\n3. displacement: continuous\n4. horsepower: continuous\n5. weight: continuous\n6. acceleration: continuous\n7. model year: multi-valued discrete\n8. origin: multi-valued discrete\n9. car name: string (unique for each instance)'

In [317]:
df.columns = ['mpg','cyl','disp','hp','wt','acc','m_year','origin','car_name']

In [318]:
df.head() # first 5 records from the dataset

mpg  cyl   disp     hp      wt   acc  m_year  origin  \
0  18.0    8  307.0  130.0  3504.0  12.0      70       1   
1  15.0    8  350.0  165.0  3693.0  11.5      70       1   
2  18.0    8  318.0  150.0  3436.0  11.0      70       1   
3  16.0    8  304.0  150.0  3433.0  12.0      70       1   
4  17.0    8  302.0  140.0  3449.0  10.5      70       1   

                    car_name  
0  chevrolet chevelle malibu  
1          buick skylark 320  
2         plymouth satellite  
3              amc rebel sst  
4                ford torino

In [ ]:
# Top 5 cars that provide maximum mileage per gallon
# Bottom 5 cars that provide mileage per gallon

# which 3 cars have highest weight
# which 3 cars have lowest weight

In [319]:
import heapq

In [320]:
heapq.nlargest(5,df.mpg)

[46.6, 44.6, 44.3, 44.0, 43.4]

In [321]:
heapq.nsmallest(5,df.mpg)

[9.0, 10.0, 10.0, 11.0, 11.0]

In [322]:
heapq.nlargest(3,df.wt)

[5140.0, 4997.0, 4955.0]

In [323]:
heapq.nsmallest(3,df.wt)

[1613.0, 1649.0, 1755.0]

In [324]:
df.shape

(398, 9)

In [325]:
sorted(df.wt,reverse=True)[0:3]

[5140.0, 4997.0, 4955.0]

In [326]:
sorted(df.wt,reverse=False)[0:3]

[1613.0, 1649.0, 1755.0]

In [327]:
df.head(10)

mpg  cyl   disp     hp      wt   acc  m_year  origin  \
0  18.0    8  307.0  130.0  3504.0  12.0      70       1   
1  15.0    8  350.0  165.0  3693.0  11.5      70       1   
2  18.0    8  318.0  150.0  3436.0  11.0      70       1   
3  16.0    8  304.0  150.0  3433.0  12.0      70       1   
4  17.0    8  302.0  140.0  3449.0  10.5      70       1   
5  15.0    8  429.0  198.0  4341.0  10.0      70       1   
6  14.0    8  454.0  220.0  4354.0   9.0      70       1   
7  14.0    8  440.0  215.0  4312.0   8.5      70       1   
8  14.0    8  455.0  225.0  4425.0  10.0      70       1   
9  15.0    8  390.0  190.0  3850.0   8.5      70       1   

                    car_name  
0  chevrolet chevelle malibu  
1          buick skylark 320  
2         plymouth satellite  
3              amc rebel sst  
4                ford torino  
5           ford galaxie 500  
6           chevrolet impala  
7          plymouth fury iii  
8           pontiac catalina  
9         amc ambassador dpl

In [328]:
df.to_dict()

{'mpg': {0: 18.0,
  1: 15.0,
  2: 18.0,
  3: 16.0,
  4: 17.0,
  5: 15.0,
  6: 14.0,
  7: 14.0,
  8: 14.0,
  9: 15.0,
  10: 15.0,
  11: 14.0,
  12: 15.0,
  13: 14.0,
  14: 24.0,
  15: 22.0,
  16: 18.0,
  17: 21.0,
  18: 27.0,
  19: 26.0,
  20: 25.0,
  21: 24.0,
  22: 25.0,
  23: 26.0,
  24: 21.0,
  25: 10.0,
  26: 10.0,
  27: 11.0,
  28: 9.0,
  29: 27.0,
  30: 28.0,
  31: 25.0,
  32: 25.0,
  33: 19.0,
  34: 16.0,
  35: 17.0,
  36: 19.0,
  37: 18.0,
  38: 14.0,
  39: 14.0,
  40: 14.0,
  41: 14.0,
  42: 12.0,
  43: 13.0,
  44: 13.0,
  45: 18.0,
  46: 22.0,
  47: 19.0,
  48: 18.0,
  49: 23.0,
  50: 28.0,
  51: 30.0,
  52: 30.0,
  53: 31.0,
  54: 35.0,
  55: 27.0,
  56: 26.0,
  57: 24.0,
  58: 25.0,
  59: 23.0,
  60: 20.0,
  61: 21.0,
  62: 13.0,
  63: 14.0,
  64: 15.0,
  65: 14.0,
  66: 17.0,
  67: 11.0,
  68: 13.0,
  69: 12.0,
  70: 13.0,
  71: 19.0,
  72: 15.0,
  73: 13.0,
  74: 13.0,
  75: 14.0,
  76: 18.0,
  77: 22.0,
  78: 21.0,
  79: 26.0,
  80: 22.0,
  81: 28.0,
  82: 23.0,
  83: 28

In [329]:
df.to_json()

'{"mpg":{"0":18.0,"1":15.0,"2":18.0,"3":16.0,"4":17.0,"5":15.0,"6":14.0,"7":14.0,"8":14.0,"9":15.0,"10":15.0,"11":14.0,"12":15.0,"13":14.0,"14":24.0,"15":22.0,"16":18.0,"17":21.0,"18":27.0,"19":26.0,"20":25.0,"21":24.0,"22":25.0,"23":26.0,"24":21.0,"25":10.0,"26":10.0,"27":11.0,"28":9.0,"29":27.0,"30":28.0,"31":25.0,"32":25.0,"33":19.0,"34":16.0,"35":17.0,"36":19.0,"37":18.0,"38":14.0,"39":14.0,"40":14.0,"41":14.0,"42":12.0,"43":13.0,"44":13.0,"45":18.0,"46":22.0,"47":19.0,"48":18.0,"49":23.0,"50":28.0,"51":30.0,"52":30.0,"53":31.0,"54":35.0,"55":27.0,"56":26.0,"57":24.0,"58":25.0,"59":23.0,"60":20.0,"61":21.0,"62":13.0,"63":14.0,"64":15.0,"65":14.0,"66":17.0,"67":11.0,"68":13.0,"69":12.0,"70":13.0,"71":19.0,"72":15.0,"73":13.0,"74":13.0,"75":14.0,"76":18.0,"77":22.0,"78":21.0,"79":26.0,"80":22.0,"81":28.0,"82":23.0,"83":28.0,"84":27.0,"85":13.0,"86":14.0,"87":13.0,"88":14.0,"89":15.0,"90":12.0,"91":13.0,"92":13.0,"93":14.0,"94":13.0,"95":12.0,"96":13.0,"97":18.0,"98":16.0,"99":18.0,"1

In [330]:
df.head()

mpg  cyl   disp     hp      wt   acc  m_year  origin  \
0  18.0    8  307.0  130.0  3504.0  12.0      70       1   
1  15.0    8  350.0  165.0  3693.0  11.5      70       1   
2  18.0    8  318.0  150.0  3436.0  11.0      70       1   
3  16.0    8  304.0  150.0  3433.0  12.0      70       1   
4  17.0    8  302.0  140.0  3449.0  10.5      70       1   

                    car_name  
0  chevrolet chevelle malibu  
1          buick skylark 320  
2         plymouth satellite  
3              amc rebel sst  
4                ford torino

In [333]:
df3 = df.tail(6)

In [334]:
df3.to_dict()

{'mpg': {392: 27.0, 393: 27.0, 394: 44.0, 395: 32.0, 396: 28.0, 397: 31.0},
 'cyl': {392: 4, 393: 4, 394: 4, 395: 4, 396: 4, 397: 4},
 'disp': {392: 151.0,
  393: 140.0,
  394: 97.0,
  395: 135.0,
  396: 120.0,
  397: 119.0},
 'hp': {392: '90.00',
  393: '86.00',
  394: '52.00',
  395: '84.00',
  396: '79.00',
  397: '82.00'},
 'wt': {392: 2950.0,
  393: 2790.0,
  394: 2130.0,
  395: 2295.0,
  396: 2625.0,
  397: 2720.0},
 'acc': {392: 17.3, 393: 15.6, 394: 24.6, 395: 11.6, 396: 18.6, 397: 19.4},
 'm_year': {392: 82, 393: 82, 394: 82, 395: 82, 396: 82, 397: 82},
 'origin': {392: 1, 393: 1, 394: 2, 395: 1, 396: 1, 397: 1},
 'car_name': {392: 'chevrolet camaro',
  393: 'ford mustang gl',
  394: 'vw pickup',
  395: 'dodge rampage',
  396: 'ford ranger',
  397: 'chevy s-10'}}

In [335]:
df3.to_dict('series')

{'mpg': 392    27.0
 393    27.0
 394    44.0
 395    32.0
 396    28.0
 397    31.0
 Name: mpg, dtype: float64,
 'cyl': 392    4
 393    4
 394    4
 395    4
 396    4
 397    4
 Name: cyl, dtype: int64,
 'disp': 392    151.0
 393    140.0
 394     97.0
 395    135.0
 396    120.0
 397    119.0
 Name: disp, dtype: float64,
 'hp': 392    90.00
 393    86.00
 394    52.00
 395    84.00
 396    79.00
 397    82.00
 Name: hp, dtype: object,
 'wt': 392    2950.0
 393    2790.0
 394    2130.0
 395    2295.0
 396    2625.0
 397    2720.0
 Name: wt, dtype: float64,
 'acc': 392    17.3
 393    15.6
 394    24.6
 395    11.6
 396    18.6
 397    19.4
 Name: acc, dtype: float64,
 'm_year': 392    82
 393    82
 394    82
 395    82
 396    82
 397    82
 Name: m_year, dtype: int64,
 'origin': 392    1
 393    1
 394    2
 395    1
 396    1
 397    1
 Name: origin, dtype: int64,
 'car_name': 392    chevrolet camaro
 393     ford mustang gl
 394           vw pickup
 395       dodge rampage
 396 

In [336]:
df3.to_dict('split')

{'index': [392, 393, 394, 395, 396, 397],
 'columns': ['mpg',
  'cyl',
  'disp',
  'hp',
  'wt',
  'acc',
  'm_year',
  'origin',
  'car_name'],
 'data': [[27.0, 4, 151.0, '90.00', 2950.0, 17.3, 82, 1, 'chevrolet camaro'],
  [27.0, 4, 140.0, '86.00', 2790.0, 15.6, 82, 1, 'ford mustang gl'],
  [44.0, 4, 97.0, '52.00', 2130.0, 24.6, 82, 2, 'vw pickup'],
  [32.0, 4, 135.0, '84.00', 2295.0, 11.6, 82, 1, 'dodge rampage'],
  [28.0, 4, 120.0, '79.00', 2625.0, 18.6, 82, 1, 'ford ranger'],
  [31.0, 4, 119.0, '82.00', 2720.0, 19.4, 82, 1, 'chevy s-10']]}

In [337]:
df3.to_dict('records')

[{'mpg': 27.0,
  'cyl': 4,
  'disp': 151.0,
  'hp': '90.00',
  'wt': 2950.0,
  'acc': 17.3,
  'm_year': 82,
  'origin': 1,
  'car_name': 'chevrolet camaro'},
 {'mpg': 27.0,
  'cyl': 4,
  'disp': 140.0,
  'hp': '86.00',
  'wt': 2790.0,
  'acc': 15.6,
  'm_year': 82,
  'origin': 1,
  'car_name': 'ford mustang gl'},
 {'mpg': 44.0,
  'cyl': 4,
  'disp': 97.0,
  'hp': '52.00',
  'wt': 2130.0,
  'acc': 24.6,
  'm_year': 82,
  'origin': 2,
  'car_name': 'vw pickup'},
 {'mpg': 32.0,
  'cyl': 4,
  'disp': 135.0,
  'hp': '84.00',
  'wt': 2295.0,
  'acc': 11.6,
  'm_year': 82,
  'origin': 1,
  'car_name': 'dodge rampage'},
 {'mpg': 28.0,
  'cyl': 4,
  'disp': 120.0,
  'hp': '79.00',
  'wt': 2625.0,
  'acc': 18.6,
  'm_year': 82,
  'origin': 1,
  'car_name': 'ford ranger'},
 {'mpg': 31.0,
  'cyl': 4,
  'disp': 119.0,
  'hp': '82.00',
  'wt': 2720.0,
  'acc': 19.4,
  'm_year': 82,
  'origin': 1,
  'car_name': 'chevy s-10'}]

In [338]:
df3.to_dict('index')

{392: {'mpg': 27.0,
  'cyl': 4,
  'disp': 151.0,
  'hp': '90.00',
  'wt': 2950.0,
  'acc': 17.3,
  'm_year': 82,
  'origin': 1,
  'car_name': 'chevrolet camaro'},
 393: {'mpg': 27.0,
  'cyl': 4,
  'disp': 140.0,
  'hp': '86.00',
  'wt': 2790.0,
  'acc': 15.6,
  'm_year': 82,
  'origin': 1,
  'car_name': 'ford mustang gl'},
 394: {'mpg': 44.0,
  'cyl': 4,
  'disp': 97.0,
  'hp': '52.00',
  'wt': 2130.0,
  'acc': 24.6,
  'm_year': 82,
  'origin': 2,
  'car_name': 'vw pickup'},
 395: {'mpg': 32.0,
  'cyl': 4,
  'disp': 135.0,
  'hp': '84.00',
  'wt': 2295.0,
  'acc': 11.6,
  'm_year': 82,
  'origin': 1,
  'car_name': 'dodge rampage'},
 396: {'mpg': 28.0,
  'cyl': 4,
  'disp': 120.0,
  'hp': '79.00',
  'wt': 2625.0,
  'acc': 18.6,
  'm_year': 82,
  'origin': 1,
  'car_name': 'ford ranger'},
 397: {'mpg': 31.0,
  'cyl': 4,
  'disp': 119.0,
  'hp': '82.00',
  'wt': 2720.0,
  'acc': 19.4,
  'm_year': 82,
  'origin': 1,
  'car_name': 'chevy s-10'}}

In [339]:
df3.to_dict('list')

{'mpg': [27.0, 27.0, 44.0, 32.0, 28.0, 31.0],
 'cyl': [4, 4, 4, 4, 4, 4],
 'disp': [151.0, 140.0, 97.0, 135.0, 120.0, 119.0],
 'hp': ['90.00', '86.00', '52.00', '84.00', '79.00', '82.00'],
 'wt': [2950.0, 2790.0, 2130.0, 2295.0, 2625.0, 2720.0],
 'acc': [17.3, 15.6, 24.6, 11.6, 18.6, 19.4],
 'm_year': [82, 82, 82, 82, 82, 82],
 'origin': [1, 1, 2, 1, 1, 1],
 'car_name': ['chevrolet camaro',
  'ford mustang gl',
  'vw pickup',
  'dodge rampage',
  'ford ranger',
  'chevy s-10']}

In [340]:
df3.to_dict()

{'mpg': {392: 27.0, 393: 27.0, 394: 44.0, 395: 32.0, 396: 28.0, 397: 31.0},
 'cyl': {392: 4, 393: 4, 394: 4, 395: 4, 396: 4, 397: 4},
 'disp': {392: 151.0,
  393: 140.0,
  394: 97.0,
  395: 135.0,
  396: 120.0,
  397: 119.0},
 'hp': {392: '90.00',
  393: '86.00',
  394: '52.00',
  395: '84.00',
  396: '79.00',
  397: '82.00'},
 'wt': {392: 2950.0,
  393: 2790.0,
  394: 2130.0,
  395: 2295.0,
  396: 2625.0,
  397: 2720.0},
 'acc': {392: 17.3, 393: 15.6, 394: 24.6, 395: 11.6, 396: 18.6, 397: 19.4},
 'm_year': {392: 82, 393: 82, 394: 82, 395: 82, 396: 82, 397: 82},
 'origin': {392: 1, 393: 1, 394: 2, 395: 1, 396: 1, 397: 1},
 'car_name': {392: 'chevrolet camaro',
  393: 'ford mustang gl',
  394: 'vw pickup',
  395: 'dodge rampage',
  396: 'ford ranger',
  397: 'chevy s-10'}}

In [342]:
from collections import OrderedDict, defaultdict

In [343]:
df3.to_dict(into=OrderedDict)

OrderedDict([('mpg',
              OrderedDict([(392, 27.0),
                           (393, 27.0),
                           (394, 44.0),
                           (395, 32.0),
                           (396, 28.0),
                           (397, 31.0)])),
             ('cyl',
              OrderedDict([(392, 4),
                           (393, 4),
                           (394, 4),
                           (395, 4),
                           (396, 4),
                           (397, 4)])),
             ('disp',
              OrderedDict([(392, 151.0),
                           (393, 140.0),
                           (394, 97.0),
                           (395, 135.0),
                           (396, 120.0),
                           (397, 119.0)])),
             ('hp',
              OrderedDict([(392, '90.00'),
                           (393, '86.00'),
                           (394, '52.00'),
                           (395, '84.00'),
                           (

In [344]:
df3.to_dict()

{'mpg': {392: 27.0, 393: 27.0, 394: 44.0, 395: 32.0, 396: 28.0, 397: 31.0},
 'cyl': {392: 4, 393: 4, 394: 4, 395: 4, 396: 4, 397: 4},
 'disp': {392: 151.0,
  393: 140.0,
  394: 97.0,
  395: 135.0,
  396: 120.0,
  397: 119.0},
 'hp': {392: '90.00',
  393: '86.00',
  394: '52.00',
  395: '84.00',
  396: '79.00',
  397: '82.00'},
 'wt': {392: 2950.0,
  393: 2790.0,
  394: 2130.0,
  395: 2295.0,
  396: 2625.0,
  397: 2720.0},
 'acc': {392: 17.3, 393: 15.6, 394: 24.6, 395: 11.6, 396: 18.6, 397: 19.4},
 'm_year': {392: 82, 393: 82, 394: 82, 395: 82, 396: 82, 397: 82},
 'origin': {392: 1, 393: 1, 394: 2, 395: 1, 396: 1, 397: 1},
 'car_name': {392: 'chevrolet camaro',
  393: 'ford mustang gl',
  394: 'vw pickup',
  395: 'dodge rampage',
  396: 'ford ranger',
  397: 'chevy s-10'}}

In [345]:
df.head()

mpg  cyl   disp     hp      wt   acc  m_year  origin  \
0  18.0    8  307.0  130.0  3504.0  12.0      70       1   
1  15.0    8  350.0  165.0  3693.0  11.5      70       1   
2  18.0    8  318.0  150.0  3436.0  11.0      70       1   
3  16.0    8  304.0  150.0  3433.0  12.0      70       1   
4  17.0    8  302.0  140.0  3449.0  10.5      70       1   

                    car_name  
0  chevrolet chevelle malibu  
1          buick skylark 320  
2         plymouth satellite  
3              amc rebel sst  
4                ford torino

In [346]:
df.at[70,'car_name']

'chrysler newport royal'

In [347]:
df.loc[70]

mpg                           13.0
cyl                              8
disp                         400.0
hp                           190.0
wt                          4422.0
acc                           12.5
m_year                          72
origin                           1
car_name    chrysler newport royal
Name: 70, dtype: object

In [348]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   mpg       398 non-null    float64
 1   cyl       398 non-null    int64  
 2   disp      398 non-null    float64
 3   hp        398 non-null    object 
 4   wt        398 non-null    float64
 5   acc       398 non-null    float64
 6   m_year    398 non-null    int64  
 7   origin    398 non-null    int64  
 8   car_name  398 non-null    object 
dtypes: float64(4), int64(3), object(2)
memory usage: 28.1+ KB


In [351]:
set(df.hp)

{'100.0',
 '102.0',
 '103.0',
 '105.0',
 '107.0',
 '108.0',
 '110.0',
 '112.0',
 '113.0',
 '115.0',
 '116.0',
 '120.0',
 '122.0',
 '125.0',
 '129.0',
 '130.0',
 '132.0',
 '133.0',
 '135.0',
 '137.0',
 '138.0',
 '139.0',
 '140.0',
 '142.0',
 '145.0',
 '148.0',
 '149.0',
 '150.0',
 '152.0',
 '153.0',
 '155.0',
 '158.0',
 '160.0',
 '165.0',
 '167.0',
 '170.0',
 '175.0',
 '180.0',
 '190.0',
 '193.0',
 '198.0',
 '200.0',
 '208.0',
 '210.0',
 '215.0',
 '220.0',
 '225.0',
 '230.0',
 '46.00',
 '48.00',
 '49.00',
 '52.00',
 '53.00',
 '54.00',
 '58.00',
 '60.00',
 '61.00',
 '62.00',
 '63.00',
 '64.00',
 '65.00',
 '66.00',
 '67.00',
 '68.00',
 '69.00',
 '70.00',
 '71.00',
 '72.00',
 '74.00',
 '75.00',
 '76.00',
 '77.00',
 '78.00',
 '79.00',
 '80.00',
 '81.00',
 '82.00',
 '83.00',
 '84.00',
 '85.00',
 '86.00',
 '87.00',
 '88.00',
 '89.00',
 '90.00',
 '91.00',
 '92.00',
 '93.00',
 '94.00',
 '95.00',
 '96.00',
 '97.00',
 '98.00',
 '?'}

In [350]:
sorted(df.hp)

['100.0',
 '100.0',
 '100.0',
 '100.0',
 '100.0',
 '100.0',
 '100.0',
 '100.0',
 '100.0',
 '100.0',
 '100.0',
 '100.0',
 '100.0',
 '100.0',
 '100.0',
 '100.0',
 '100.0',
 '102.0',
 '103.0',
 '105.0',
 '105.0',
 '105.0',
 '105.0',
 '105.0',
 '105.0',
 '105.0',
 '105.0',
 '105.0',
 '105.0',
 '105.0',
 '105.0',
 '107.0',
 '108.0',
 '110.0',
 '110.0',
 '110.0',
 '110.0',
 '110.0',
 '110.0',
 '110.0',
 '110.0',
 '110.0',
 '110.0',
 '110.0',
 '110.0',
 '110.0',
 '110.0',
 '110.0',
 '110.0',
 '110.0',
 '110.0',
 '112.0',
 '112.0',
 '112.0',
 '113.0',
 '115.0',
 '115.0',
 '115.0',
 '115.0',
 '115.0',
 '116.0',
 '120.0',
 '120.0',
 '120.0',
 '120.0',
 '122.0',
 '125.0',
 '125.0',
 '125.0',
 '129.0',
 '129.0',
 '130.0',
 '130.0',
 '130.0',
 '130.0',
 '130.0',
 '132.0',
 '133.0',
 '135.0',
 '137.0',
 '138.0',
 '139.0',
 '139.0',
 '140.0',
 '140.0',
 '140.0',
 '140.0',
 '140.0',
 '140.0',
 '140.0',
 '142.0',
 '145.0',
 '145.0',
 '145.0',
 '145.0',
 '145.0',
 '145.0',
 '145.0',
 '148.0',
 '149.0',


In [352]:
df.head()

mpg  cyl   disp     hp      wt   acc  m_year  origin  \
0  18.0    8  307.0  130.0  3504.0  12.0      70       1   
1  15.0    8  350.0  165.0  3693.0  11.5      70       1   
2  18.0    8  318.0  150.0  3436.0  11.0      70       1   
3  16.0    8  304.0  150.0  3433.0  12.0      70       1   
4  17.0    8  302.0  140.0  3449.0  10.5      70       1   

                    car_name  
0  chevrolet chevelle malibu  
1          buick skylark 320  
2         plymouth satellite  
3              amc rebel sst  
4                ford torino

In [353]:
df.replace("?",0,inplace=True)

In [354]:
df.hp.describe()

count       398
unique       94
top       150.0
freq         22
Name: hp, dtype: object

In [355]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   mpg       398 non-null    float64
 1   cyl       398 non-null    int64  
 2   disp      398 non-null    float64
 3   hp        398 non-null    object 
 4   wt        398 non-null    float64
 5   acc       398 non-null    float64
 6   m_year    398 non-null    int64  
 7   origin    398 non-null    int64  
 8   car_name  398 non-null    object 
dtypes: float64(4), int64(3), object(2)
memory usage: 28.1+ KB


In [356]:
df.hp = pd.Series(df.hp).astype('float64')

In [357]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   mpg       398 non-null    float64
 1   cyl       398 non-null    int64  
 2   disp      398 non-null    float64
 3   hp        398 non-null    float64
 4   wt        398 non-null    float64
 5   acc       398 non-null    float64
 6   m_year    398 non-null    int64  
 7   origin    398 non-null    int64  
 8   car_name  398 non-null    object 
dtypes: float64(5), int64(3), object(1)
memory usage: 28.1+ KB


In [358]:
d = df3.to_dict('list')

In [359]:
d

{'mpg': [27.0, 27.0, 44.0, 32.0, 28.0, 31.0],
 'cyl': [4, 4, 4, 4, 4, 4],
 'disp': [151.0, 140.0, 97.0, 135.0, 120.0, 119.0],
 'hp': ['90.00', '86.00', '52.00', '84.00', '79.00', '82.00'],
 'wt': [2950.0, 2790.0, 2130.0, 2295.0, 2625.0, 2720.0],
 'acc': [17.3, 15.6, 24.6, 11.6, 18.6, 19.4],
 'm_year': [82, 82, 82, 82, 82, 82],
 'origin': [1, 1, 2, 1, 1, 1],
 'car_name': ['chevrolet camaro',
  'ford mustang gl',
  'vw pickup',
  'dodge rampage',
  'ford ranger',
  'chevy s-10']}

In [360]:
d.keys()

dict_keys(['mpg', 'cyl', 'disp', 'hp', 'wt', 'acc', 'm_year', 'origin', 'car_name'])

In [361]:
d.items()

dict_items([('mpg', [27.0, 27.0, 44.0, 32.0, 28.0, 31.0]), ('cyl', [4, 4, 4, 4, 4, 4]), ('disp', [151.0, 140.0, 97.0, 135.0, 120.0, 119.0]), ('hp', ['90.00', '86.00', '52.00', '84.00', '79.00', '82.00']), ('wt', [2950.0, 2790.0, 2130.0, 2295.0, 2625.0, 2720.0]), ('acc', [17.3, 15.6, 24.6, 11.6, 18.6, 19.4]), ('m_year', [82, 82, 82, 82, 82, 82]), ('origin', [1, 1, 2, 1, 1, 1]), ('car_name', ['chevrolet camaro', 'ford mustang gl', 'vw pickup', 'dodge rampage', 'ford ranger', 'chevy s-10'])])

In [362]:
d.values()

dict_values([[27.0, 27.0, 44.0, 32.0, 28.0, 31.0], [4, 4, 4, 4, 4, 4], [151.0, 140.0, 97.0, 135.0, 120.0, 119.0], ['90.00', '86.00', '52.00', '84.00', '79.00', '82.00'], [2950.0, 2790.0, 2130.0, 2295.0, 2625.0, 2720.0], [17.3, 15.6, 24.6, 11.6, 18.6, 19.4], [82, 82, 82, 82, 82, 82], [1, 1, 2, 1, 1, 1], ['chevrolet camaro', 'ford mustang gl', 'vw pickup', 'dodge rampage', 'ford ranger', 'chevy s-10']])

In [363]:
# minimum mileage
d.values()

dict_values([[27.0, 27.0, 44.0, 32.0, 28.0, 31.0], [4, 4, 4, 4, 4, 4], [151.0, 140.0, 97.0, 135.0, 120.0, 119.0], ['90.00', '86.00', '52.00', '84.00', '79.00', '82.00'], [2950.0, 2790.0, 2130.0, 2295.0, 2625.0, 2720.0], [17.3, 15.6, 24.6, 11.6, 18.6, 19.4], [82, 82, 82, 82, 82, 82], [1, 1, 2, 1, 1, 1], ['chevrolet camaro', 'ford mustang gl', 'vw pickup', 'dodge rampage', 'ford ranger', 'chevy s-10']])

In [364]:
mpg = {'ford': 24,
      "bmw": 27,
      'fords': 23,
      'chvy': 25}

In [365]:
mpg

{'ford': 24, 'bmw': 27, 'fords': 23, 'chvy': 25}

In [366]:
min(zip(mpg.values(),mpg.keys()))

(23, 'fords')

In [367]:
max(zip(mpg.values(),mpg.keys()))

(27, 'bmw')

In [368]:
# what are the car brands that are most frequently

In [369]:
cars = list(df.car_name)

In [370]:
from collections import Counter

In [371]:
counts = Counter(cars)

In [372]:
counts.most_common(5)

[('ford pinto', 6),
 ('ford maverick', 5),
 ('amc matador', 5),
 ('toyota corolla', 5),
 ('chevrolet impala', 4)]

In [373]:
counts

Counter({'chevrolet chevelle malibu': 2,
         'buick skylark 320': 1,
         'plymouth satellite': 1,
         'amc rebel sst': 1,
         'ford torino': 1,
         'ford galaxie 500': 3,
         'chevrolet impala': 4,
         'plymouth fury iii': 3,
         'pontiac catalina': 3,
         'amc ambassador dpl': 1,
         'dodge challenger se': 1,
         "plymouth 'cuda 340": 1,
         'chevrolet monte carlo': 1,
         'buick estate wagon (sw)': 2,
         'toyota corona mark ii': 1,
         'plymouth duster': 3,
         'amc hornet': 4,
         'ford maverick': 5,
         'datsun pl510': 2,
         'volkswagen 1131 deluxe sedan': 1,
         'peugeot 504': 4,
         'audi 100 ls': 1,
         'saab 99e': 1,
         'bmw 2002': 1,
         'amc gremlin': 4,
         'ford f250': 1,
         'chevy c20': 1,
         'dodge d200': 1,
         'hi 1200d': 1,
         'chevrolet vega 2300': 1,
         'toyota corona': 4,
         'ford pinto': 6,
         'plym